### ISSUE TITLE
Document your tests

### ISSUE THREAD

**Issue by BrenoOR** [MaracatronicsRobotics/Armorial-Micro#11]
# This issue is for tests on Radios and tests on VSSS
Document every test made. Pasting a link for full detailed documentations for each issue.

- [x] Describe your test list (what kind of tests are you making)
- [x] Create a document and link to every issue.
- [x] Describe dates and methods used on tests. (Make a full report)
- [x] Compare with previous tests made.

**Comment by ViniciusAlvesPereira** [comment]
Link de documentação de micro do VSSS: https://www.notion.so/Documenta-o-Micro-VSSS-d08ea901f7a14309a8b901972cc3a87a?pvs=4
